
export const countries =
{
  USA: 'أمريكا',
  Spain: 'إسبانيا',
  Italy: 'إيطاليا',
  Germany: 'ألمانيا',
  France: 'فرنسا',
  Iran: 'إيران',
  UK: 'بريطانيا',
  Turkey: 'تركيا',
  Switzerland: 'سويسرا',
  Belgium: 'بلجيكا',
  Netherlands: 'هولندا',
  Canada: 'كندا',
  Austria: 'النمسا',
  Portugal: 'البرتغال',
  Brazil: 'البرازيل',
  'S. Korea': 'كوريا الجنوبية',
  Israel: 'الاحتلال الإسرائيلي',
  Sweden: 'السويد',
  Norway: 'النرويج',
  Australia: 'أستراليا',
  Russia: 'روسيا',
  Ireland: 'أيرلندا',
  Czechia: 'تشيك',
  Chile: 'شيلي',
  Denmark: 'الدنمارك',
  Poland: 'بولندا',
  Romania: 'رومانيا',
  Malaysia: 'ماليزيا',
  Ecuador: 'إكوادور',
  Philippines: 'الفلبين',
  India: 'الهند',
  Japan: 'اليابان',
  Pakistan: 'باكستان',
  Luxembourg: 'لوكسمبورغ',
  'Saudi Arabia': 'السعودية',
  Indonesia: 'إندونيسيا',
  Thailand: 'تايلاند',
  Finland: 'فنلندا',
  Peru: 'بيرو',
  Mexico: 'المكسيك',
  Greece: 'اليونان',
  Panama: 'بنما',
  Serbia: 'صربيا',
  'South Africa': 'جنوب أفريقيا',
  UAE: 'الإمارات',
  'Dominican Republic': 'جمهورية الدومينيكان',
  Iceland: 'أيسلندا',
  Colombia: 'كولومبيا',
  Argentina: 'الأرجنتين',
  Qatar: 'قطر',
  Algeria: 'الجزائر',
  Ukraine: 'أوكرانيا',
  Singapore: 'سنغافورة',
  Croatia: 'كرواتيا',
  Egypt: 'مصر',
  Estonia: 'إستونيا',
  Slovenia: 'سلوفينيا',
  'New Zealand': 'نيوزيلندا',
  Morocco: 'المغرب',
  Iraq: 'العراق',
  'Hong Kong': 'هونغ كونغ',
  Lithuania: 'ليتوانيا',
  Armenia: 'أرمينيا',
  Moldova: 'مولدوفا',
  'Diamond Princess': 'الماس الأميرة',
  Bahrain: 'البحرين',
  Hungary: 'المجر',
  'Bosnia and Herzegovina': 'البوسنة والهرسك',
  Cameroon: 'الكاميرون',
  Tunisia: 'تونس',
  Kazakhstan: 'كازاخستان',
  Azerbaijan: 'أذربيجان',
  Lebanon: 'لبنان',
  Latvia: 'لاتفيا',
  Bulgaria: 'بلغاريا',
  'North Macedonia': 'شمال مقدونيا',
  Kuwait: 'الكويت',
  Slovakia: 'سلوفاكيا',
  Andorra: 'أندورا',
  Belarus: 'روسيا البيضاء',
  'Costa Rica': 'كوستاريكا',
  Cyprus: 'قبرص',
  Uruguay: 'أوروغواي',
  Taiwan: 'تايوان',
  Réunion: 'ريونيون',
  Albania: 'ألبانيا',
  Jordan: 'الأردن',
  'Burkina Faso': 'بوركينا فاسو',
  Afghanistan: 'أفغانستان',
  Cuba: 'كوبا',
  Oman: 'عمان',
  Uzbekistan: 'أوزبكستان',
  Honduras: 'هندوراس',
  'Channel Islands': 'جزر القناة',
  'San Marino': 'سان مارينو',
  'Ivory Coast': 'ساحل العاج',
  Vietnam: 'فيتنام',
  Senegal: 'السنغال',
  Palestine: 'فلسطين',
  Nigeria: 'نيجيريا',
  Malta: 'مالطا',
  Ghana: 'غانا',
  Montenegro: 'الجبل الأسود',
  Mauritius: 'موريشيوس',
  'Faeroe Islands': 'جزر فارو',
  'Sri Lanka': 'سري لانكا',
  Georgia: 'جورجيا',
  Venezuela: 'فنزويلا',
  DRC: 'جمهورية الكونغو الديمقراطية',
  Martinique: 'مارتينيك',
  Niger: 'النيجر',
  Kyrgyzstan: 'قيرغيزستان',
  Bolivia: 'بوليفيا',
  Brunei: 'روني',
  Guadeloupe: 'غوادلوب',
  Mayotte: 'مايوت',
  Kenya: 'كينيا',
  'Isle of Man': 'مان',
  Cambodia: 'كمبوديا',
  Guinea: 'غينيا',
  'Trinidad and Tobago': 'ترينيداد وتوباغو',
  Rwanda: 'رواندا',
  Gibraltar: 'طارق',
  Paraguay: 'باراغواي',
  Liechtenstein: 'ليختنشتاين',
  Bangladesh: 'بنغلاديش',
  Madagascar: 'مدغشقر',
  Monaco: 'موناكو',
  Aruba: 'أروبا',
  Guatemala: 'غواتيمالا',
  'French Guiana': 'غويانا الفرنسية',
  'El Salvador': 'السلفادور',
  Jamaica: 'جامايكا',
  Barbados: 'بربادوس',
  Djibouti: 'جيبوتي',
  Uganda: 'أوغندا',
  Macao: 'ماكاو',
  Mali: 'مالي',
  Togo: 'توغو',
  'French Polynesia': 'بولينيزيا الفرنسية',
  Zambia: 'زامبيا',
  Ethiopia: 'إثيوبيا',
  'Cayman Islands': 'جزر كايمان',
  Bermuda: 'برمودا',
  Eritrea: 'إريتريا',
  Bahamas: 'جزر البهاما',
  'Saint Martin': 'سانت مارتن',
  Guyana: 'غيانا',
  'Sint Maarten': 'سانت مارتن',
  Congo: 'الكونغو',
  Gabon: 'غابون',
  Myanmar: 'ميانمار',
  Tanzania: 'تنزانيا',
  Haiti: 'هايتي',
  Maldives: 'جزر المالديف',
  'Guinea-Bissau': 'غينيا-بيساو',
  Libya: 'ليبيا',
  'New Caledonia': 'كاليدونيا الجديدة',
  Syria: 'سوريا',
  Benin: 'بنن',
  'Equatorial Guinea': 'غينيا الاستوائية',
  'Antigua and Barbuda': 'أنتيغوا وبربودا',
  Dominica: 'دومينيكا',
  Mongolia: 'منغوليا',
  Namibia: 'ناميبيا',
  'Saint Lucia': 'سانت لوسيا',
  Fiji: 'فيجي',
  Grenada: 'غرينادا',
  Curaçao: 'كوراساو',
  Greenland: 'غرينلاند',
  Angola: 'أنغولا',
  Sudan: 'السودان',
  Liberia: 'ليبريا',
  Suriname: 'سورينام',
  Laos: 'لاوس',
  Mozambique: 'موزامبيق',
  Seychelles: 'سيشيل',
  'MS Zaandam': 'MS زاندام',
  Zimbabwe: 'زمبابوي',
  Nepal: 'نيبال',
  Chad: 'تشاد',
  'Saint Kitts and Nevis': 'سانت كيتس ونيفيس',
  Eswatini: 'Eswatini',
  CAR: 'السيارة',
  'Cabo Verde': 'كابو فيردي',
  'Vatican City': 'مدينة الفاتيكان',
  'St. Vincent Grenadines': 'سانت فنسنت وغرنادين',
  Somalia: 'الصومال',
  Mauritania: 'موريتانيا',
  Montserrat: 'مونتسيرات',
  'St. Barth': 'سانت بارث',
  Nicaragua: 'نيكاراغوا',
  Bhutan: 'بوتان',
  'Turks and Caicos': 'جزر تركس وكايكوس',
  Botswana: 'بوتسوانا',
  Gambia: 'غامبيا',
  Belize: 'بليز',
  Malawi: 'ملاوي',
  'Sierra Leone': 'سيراليون',
  Anguilla: 'أنغيلا',
  'British Virgin Islands': 'جزر فيرجن البريطانية',
  Burundi: 'بوروندي',
  'Caribbean Netherlands': 'الجزر الكاريبية الهولندية',
  'Falkland Islands': 'جزر فوكلاند',
  'Papua New Guinea': 'بابوا غينيا الجديدة',
  'Timor-Leste': 'تيمور-ليشتي',
  China: 'الصين'
}
